#!/usr/bin/python3

# Verda Ŝtelo - An anagram game in Esperanto for the web
# Copyright (C) 2022, 2024  Neil Roberts
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

import sys

HEADER="""\
/* Automatically generated by make-crc-table.py */

static const uint32_t
crc_table[256] = {\
"""

FOOTER="""\
};\
"""

with open(sys.argv[1], "w", encoding="utf-8") as out:
    print(HEADER, file = out)

    for n in range(256):
        c = n

        for bit in range(8):
            value = c & 1

            c >>= 1

            if value != 0:
                c ^= 0xedb88320

        print(f"        0x{c & 0xffffffff:08x},", file = out)

    print(FOOTER, file = out)
